/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GiftListIndexRouteImport } from './routes/giftList/index'
import { Route as Attendance4IndexRouteImport } from './routes/attendance4/index'
import { Route as Attendance3IndexRouteImport } from './routes/attendance3/index'
import { Route as Attendance2IndexRouteImport } from './routes/attendance2/index'
import { Route as Attendance1IndexRouteImport } from './routes/attendance1/index'
import { Route as CheckoutSuccessIndexRouteImport } from './routes/checkout/success/index'
import { Route as CheckoutPendingIndexRouteImport } from './routes/checkout/pending/index'
import { Route as CheckoutFailureIndexRouteImport } from './routes/checkout/failure/index'

const GiftListIndexRoute = GiftListIndexRouteImport.update({
  id: '/giftList/',
  path: '/giftList/',
  getParentRoute: () => rootRouteImport,
} as any)
const Attendance4IndexRoute = Attendance4IndexRouteImport.update({
  id: '/attendance4/',
  path: '/attendance4/',
  getParentRoute: () => rootRouteImport,
} as any)
const Attendance3IndexRoute = Attendance3IndexRouteImport.update({
  id: '/attendance3/',
  path: '/attendance3/',
  getParentRoute: () => rootRouteImport,
} as any)
const Attendance2IndexRoute = Attendance2IndexRouteImport.update({
  id: '/attendance2/',
  path: '/attendance2/',
  getParentRoute: () => rootRouteImport,
} as any)
const Attendance1IndexRoute = Attendance1IndexRouteImport.update({
  id: '/attendance1/',
  path: '/attendance1/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessIndexRoute = CheckoutSuccessIndexRouteImport.update({
  id: '/checkout/success/',
  path: '/checkout/success/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPendingIndexRoute = CheckoutPendingIndexRouteImport.update({
  id: '/checkout/pending/',
  path: '/checkout/pending/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutFailureIndexRoute = CheckoutFailureIndexRouteImport.update({
  id: '/checkout/failure/',
  path: '/checkout/failure/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/attendance1/': typeof Attendance1IndexRoute
  '/attendance2/': typeof Attendance2IndexRoute
  '/attendance3/': typeof Attendance3IndexRoute
  '/attendance4/': typeof Attendance4IndexRoute
  '/giftList/': typeof GiftListIndexRoute
  '/checkout/failure/': typeof CheckoutFailureIndexRoute
  '/checkout/pending/': typeof CheckoutPendingIndexRoute
  '/checkout/success/': typeof CheckoutSuccessIndexRoute
}
export interface FileRoutesByTo {
  '/attendance1': typeof Attendance1IndexRoute
  '/attendance2': typeof Attendance2IndexRoute
  '/attendance3': typeof Attendance3IndexRoute
  '/attendance4': typeof Attendance4IndexRoute
  '/giftList': typeof GiftListIndexRoute
  '/checkout/failure': typeof CheckoutFailureIndexRoute
  '/checkout/pending': typeof CheckoutPendingIndexRoute
  '/checkout/success': typeof CheckoutSuccessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/attendance1/': typeof Attendance1IndexRoute
  '/attendance2/': typeof Attendance2IndexRoute
  '/attendance3/': typeof Attendance3IndexRoute
  '/attendance4/': typeof Attendance4IndexRoute
  '/giftList/': typeof GiftListIndexRoute
  '/checkout/failure/': typeof CheckoutFailureIndexRoute
  '/checkout/pending/': typeof CheckoutPendingIndexRoute
  '/checkout/success/': typeof CheckoutSuccessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/attendance1/'
    | '/attendance2/'
    | '/attendance3/'
    | '/attendance4/'
    | '/giftList/'
    | '/checkout/failure/'
    | '/checkout/pending/'
    | '/checkout/success/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/attendance1'
    | '/attendance2'
    | '/attendance3'
    | '/attendance4'
    | '/giftList'
    | '/checkout/failure'
    | '/checkout/pending'
    | '/checkout/success'
  id:
    | '__root__'
    | '/attendance1/'
    | '/attendance2/'
    | '/attendance3/'
    | '/attendance4/'
    | '/giftList/'
    | '/checkout/failure/'
    | '/checkout/pending/'
    | '/checkout/success/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Attendance1IndexRoute: typeof Attendance1IndexRoute
  Attendance2IndexRoute: typeof Attendance2IndexRoute
  Attendance3IndexRoute: typeof Attendance3IndexRoute
  Attendance4IndexRoute: typeof Attendance4IndexRoute
  GiftListIndexRoute: typeof GiftListIndexRoute
  CheckoutFailureIndexRoute: typeof CheckoutFailureIndexRoute
  CheckoutPendingIndexRoute: typeof CheckoutPendingIndexRoute
  CheckoutSuccessIndexRoute: typeof CheckoutSuccessIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/giftList/': {
      id: '/giftList/'
      path: '/giftList'
      fullPath: '/giftList/'
      preLoaderRoute: typeof GiftListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance4/': {
      id: '/attendance4/'
      path: '/attendance4'
      fullPath: '/attendance4/'
      preLoaderRoute: typeof Attendance4IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance3/': {
      id: '/attendance3/'
      path: '/attendance3'
      fullPath: '/attendance3/'
      preLoaderRoute: typeof Attendance3IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance2/': {
      id: '/attendance2/'
      path: '/attendance2'
      fullPath: '/attendance2/'
      preLoaderRoute: typeof Attendance2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance1/': {
      id: '/attendance1/'
      path: '/attendance1'
      fullPath: '/attendance1/'
      preLoaderRoute: typeof Attendance1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success/': {
      id: '/checkout/success/'
      path: '/checkout/success'
      fullPath: '/checkout/success/'
      preLoaderRoute: typeof CheckoutSuccessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/pending/': {
      id: '/checkout/pending/'
      path: '/checkout/pending'
      fullPath: '/checkout/pending/'
      preLoaderRoute: typeof CheckoutPendingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/failure/': {
      id: '/checkout/failure/'
      path: '/checkout/failure'
      fullPath: '/checkout/failure/'
      preLoaderRoute: typeof CheckoutFailureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  Attendance1IndexRoute: Attendance1IndexRoute,
  Attendance2IndexRoute: Attendance2IndexRoute,
  Attendance3IndexRoute: Attendance3IndexRoute,
  Attendance4IndexRoute: Attendance4IndexRoute,
  GiftListIndexRoute: GiftListIndexRoute,
  CheckoutFailureIndexRoute: CheckoutFailureIndexRoute,
  CheckoutPendingIndexRoute: CheckoutPendingIndexRoute,
  CheckoutSuccessIndexRoute: CheckoutSuccessIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
